from __future__ import annotations

import re


KNOWN_REASON_CODES = frozenset({
    "ATTACHMENT_DISCOVERED",
    "AUTHORITY_FAILED",
    "BINARY_IDENTITY_EXTRACTION_FAILED",
    "BINARY_NOT_FETCHED",
    "DOCUMENT_NOT_FOUND",
    "DOWNLOAD_CONTROL",
    "EVIDENCE_INCOMPLETE",
    "FETCH_ERROR",
    "FINAL_URL_OUTSIDE_ALLOWLIST",
    "HTTPS_REQUIRED",
    "IDENTIFIER_MISSING",
    "IDENTITY_FAILED",
    "IDENTITY_MATCH",
    "IDENTITY_MISMATCH",
    "IDENTITY_NOT_FOUND",
    "MIME_MAGIC_MISMATCH",
    "NETWORK_DISABLED",
    "NETWORK_ERROR",
    "NETWORK_RETRY_EXHAUSTED",
    "OPTIONAL_DEFERRED",
    "PAGE_URL_OUTSIDE_ALLOWLIST",
    "PLAYWRIGHT_DISABLED",
    "PLAYWRIGHT_DOWNLOAD_OUTSIDE_ALLOWLIST",
    "PLAYWRIGHT_NOT_INSTALLED",
    "PLAYWRIGHT_SELECTOR_NOT_PROVEN",
    "PROVIDER_NOT_ALLOWED",
    "REDIRECT_LIMIT",
    "REDIRECT_WITHOUT_LOCATION",
    "SECONDARY_SOURCE",
    "SHA_MISMATCH",
    "SIZE_LIMIT",
    "UNKNOWN_MAGIC",
    "URL_ENCODING_FAILED",
    "URL_OUTSIDE_ALLOWLIST",
    "VBPL_HOME_SHELL",
})

CODE_ERROR_REASONS = frozenset({"FETCH_ERROR", "URL_ENCODING_FAILED"})
RETRYABLE_REASONS = frozenset({"NETWORK_ERROR"})


def is_known_reason(code: str) -> bool:
    return code in KNOWN_REASON_CODES or bool(re.fullmatch(r"HTTP_[1-5][0-9]{2}", code))
