overrides:
  28nd.signed.pdf:
    document_number: 28/2015/NĐ-CP
    document_type: HISTORICAL
  326_2016_UBTVQH14(16723).pdf:
    document_number: 326/2016/UBTVQH14
    issuer: Ủy ban Thường vụ Quốc hội
