import { Check, ChevronDown, SlidersHorizontal } from 'lucide-react'

export function SettingsPage({ theme, setTheme }) {
  return <main className="utility-page"><header><span className="eyebrow">WORKSPACE</span><h1>Cài đặt</h1><p>Tùy chỉnh trải nghiệm nghiên cứu pháp lý của bạn.</p></header><div className="settings-grid">
    <section className="settings-card"><h2>Giao diện</h2><p>Chọn chế độ hiển thị phù hợp với môi trường làm việc.</p><div className="appearance-options">{[['light','Sáng'],['dark','Tối'],['system','Theo hệ thống']].map(([value,label]) => <button key={value} className={theme === value ? 'selected' : ''} onClick={() => setTheme(value)}><span className={`theme-preview ${value}`} />{label}{theme === value && <Check size={16} />}</button>)}</div></section>
    <section className="settings-card"><h2>Trò chuyện</h2><label className="setting-row"><span><strong>Enter để gửi</strong><small>Shift + Enter để xuống dòng</small></span><input type="checkbox" defaultChecked /></label><label className="setting-row"><span><strong>Hiển thị thời gian</strong><small>Hiển thị thời điểm của mỗi tin nhắn</small></span><input type="checkbox" defaultChecked /></label><label className="setting-row"><span><strong>Tự động cuộn</strong><small>Di chuyển đến tin nhắn mới nhất</small></span><input type="checkbox" defaultChecked /></label></section>
    <section className="settings-card"><h2>AI & nguồn</h2><label className="select-field">Mô hình phản hồi<select defaultValue="research"><option value="research">Nghiên cứu pháp lý</option><option>Ngắn gọn</option><option>Phân tích chi tiết</option></select><ChevronDown size={16} /></label><label className="select-field">Ưu tiên trích dẫn<select defaultValue="inline"><option value="inline">Trong nội dung trả lời</option><option>Chỉ hiện thẻ nguồn</option></select><ChevronDown size={16} /></label><p className="settings-note"><SlidersHorizontal size={15} /> Các lựa chọn này sẵn sàng liên kết với cấu hình backend sau này.</p></section>
  </div></main>
}
