"""One-command local orchestrator for the full Kaggle ONLINE backend.

The script keeps one stable Kaggle kernel ID, generates a deterministic private
notebook, starts or reuses its latest run, mirrors logs locally, discovers the
ngrok endpoint, updates ``frontend/.env``, verifies ``/ready`` and optionally
starts the local Vite frontend.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "config/kaggle_online_cli.yaml"
URL_PATTERN = re.compile(r"REMOTE_BACKEND_URL=(https://[^\s\x1b]+)")
TERMINAL_STATES = {"complete", "error", "cancelled", "canceled"}
ACTIVE_STATES = {"running", "queued"}


class AutomationError(RuntimeError):
    pass


def load_settings(path: Path) -> dict:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    settings = dict(raw.get("kaggle_online") or raw)
    required = ("kernel", "title", "dataset_sources", "repo_url")
    missing = [key for key in required if not settings.get(key)]
    if missing:
        raise AutomationError("Missing Kaggle ONLINE settings: " + ", ".join(missing))
    if "/" not in settings["kernel"]:
        raise AutomationError("kernel must use owner/slug format")
    return settings


def run_capture(args: list[str], *, cwd: Path = ROOT, check: bool = False) -> subprocess.CompletedProcess:
    env = os.environ.copy()
    env.setdefault("PYTHONUTF8", "1")
    result = subprocess.run(args, cwd=cwd, env=env, text=True, encoding="utf-8",
                            errors="replace", stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT)
    if check and result.returncode:
        raise AutomationError(f"Command failed ({result.returncode}): {' '.join(args)}\n{result.stdout}")
    return result


def find_kaggle_cli() -> str | None:
    name = "kaggle.exe" if os.name == "nt" else "kaggle"
    beside_python = Path(sys.executable).resolve().parent / name
    if beside_python.is_file():
        return str(beside_python)
    return shutil.which("kaggle")


def ensure_kaggle_cli() -> str:
    executable = find_kaggle_cli()
    if executable:
        return executable
    print("Kaggle CLI chưa có; đang cài bản chính thức mới nhất...", flush=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "kaggle"], check=True)
    executable = find_kaggle_cli()
    if not executable:
        raise AutomationError("Kaggle CLI was installed but its executable was not found")
    return executable


def ensure_authentication(kaggle: str) -> None:
    probe = run_capture([kaggle, "kernels", "list", "--mine"])
    if probe.returncode == 0:
        return
    print("Kaggle CLI chưa được xác thực; bắt đầu đăng nhập một lần...", flush=True)
    subprocess.run([kaggle, "auth", "login"], check=True)
    probe = run_capture([kaggle, "kernels", "list", "--mine"])
    if probe.returncode:
        raise AutomationError("Kaggle authentication failed:\n" + probe.stdout)


def git_ref() -> str:
    result = run_capture(["git", "rev-parse", "HEAD"], check=True)
    return result.stdout.strip()


def automation_fingerprint(settings: dict, ref: str) -> str:
    material = {
        "schema": 1,
        "kernel": settings["kernel"],
        "datasets": settings["dataset_sources"],
        "machine_shape": settings.get("machine_shape", "NvidiaTeslaT4"),
        "repo_url": settings["repo_url"],
        "repo_ref": ref,
    }
    return hashlib.sha256(json.dumps(material, sort_keys=True).encode()).hexdigest()


def notebook_source(settings: dict, ref: str, fingerprint: str) -> str:
    repo_url = json.dumps(settings["repo_url"])
    repo_ref = json.dumps(ref)
    marker = json.dumps(fingerprint)
    return f'''# Generated by scripts/kaggle_online_cli.py; do not put secrets here.
import os
from pathlib import Path
import shutil
import subprocess
import sys

AUTOMATION_FINGERPRINT = {marker}
REPOSITORY = {repo_url}
REPOSITORY_REF = {repo_ref}
ROOT = Path("/kaggle/working/legal-agentic-rag")

def run(arguments, cwd=None):
    print("+", " ".join(map(str, arguments)), flush=True)
    subprocess.run(list(map(str, arguments)), cwd=cwd, check=True)

if ROOT.exists():
    shutil.rmtree(ROOT)
run(["git", "clone", "--filter=blob:none", "--no-checkout", REPOSITORY, ROOT])
run(["git", "checkout", "--detach", REPOSITORY_REF], cwd=ROOT)
run([sys.executable, "-m", "pip", "install", "--disable-pip-version-check", "-q",
     "-e", str(ROOT) + "[retrieval,online]", "ngrok"])
if not shutil.which("ollama"):
    run(["bash", "-lc", "curl -fsSL https://ollama.com/install.sh | sh"])
os.chdir(ROOT)
run([sys.executable, "kaggle/online_remote.py"])
'''


def write_kernel_bundle(settings: dict, ref: str, fingerprint: str) -> Path:
    folder = ROOT / settings.get("build_dir", "build/kaggle_online_cli")
    folder.mkdir(parents=True, exist_ok=True)
    notebook_name = "vn_labor_online_full.ipynb"
    source = notebook_source(settings, ref, fingerprint)
    notebook = {
        "cells": [{"cell_type": "code", "execution_count": None, "metadata": {},
                   "outputs": [], "source": source.splitlines(keepends=True)}],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    metadata = {
        "id": settings["kernel"],
        "title": settings["title"],
        "code_file": notebook_name,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "machine_shape": settings.get("machine_shape", "NvidiaTeslaT4"),
        "dataset_sources": list(settings["dataset_sources"]),
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }
    (folder / notebook_name).write_text(json.dumps(notebook, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (folder / "kernel-metadata.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return folder


def parse_status(text: str) -> str:
    folded = text.casefold()
    for status in ("running", "queued", "complete", "error", "cancelled", "canceled"):
        if re.search(rf"\b{status}\b", folded):
            return status
    return "unknown"


def kernel_status(kaggle: str, handle: str) -> tuple[bool, str, str]:
    result = run_capture([kaggle, "kernels", "status", handle])
    if result.returncode:
        return False, "missing", result.stdout
    return True, parse_status(result.stdout), result.stdout


def extract_url(text: str) -> str | None:
    matches = URL_PATTERN.findall(text)
    return matches[-1].rstrip(".,;\")'") if matches else None


def fetch_logs(kaggle: str, handle: str) -> subprocess.CompletedProcess:
    return run_capture([kaggle, "kernels", "logs", handle])


def wait_for_backend_url(kaggle: str, settings: dict) -> tuple[str, Path]:
    handle = settings["kernel"]
    timeout = int(settings.get("startup_timeout_seconds", 2400))
    interval = max(5, int(settings.get("poll_seconds", 15)))
    log_dir = ROOT / settings.get("log_dir", "artifacts/kaggle_online")
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / (handle.replace("/", "_") + ".log")
    deadline = time.monotonic() + timeout
    previous_lines = 0
    last_logs = ""
    while time.monotonic() < deadline:
        logs = fetch_logs(kaggle, handle)
        if logs.returncode == 0:
            last_logs = logs.stdout
            log_path.write_text(last_logs, encoding="utf-8")
            lines = last_logs.splitlines()
            for line in lines[previous_lines:]:
                print(line, flush=True)
            previous_lines = len(lines)
            url = extract_url(last_logs)
            if url:
                return url, log_path
            if "Missing Kaggle Secret:" in last_logs:
                raise AutomationError(
                    "Notebook chưa được cấp Secrets. Mở https://www.kaggle.com/code/" + handle +
                    ", vào Add-ons → Secrets, bật VN_LABOR_API_KEY và NGROK_AUTHTOKEN "
                    "(HF_TOKEN/NGROK_DOMAIN tùy chọn), rồi chạy lại cùng lệnh."
                )
        exists, status, status_text = kernel_status(kaggle, handle)
        if exists and status in TERMINAL_STATES:
            raise AutomationError(f"Kaggle kernel ended with status {status}. Log: {log_path}\n{last_logs[-6000:]}")
        if not exists:
            print(status_text, flush=True)
        time.sleep(interval)
    raise AutomationError(f"Timed out waiting for REMOTE_BACKEND_URL. Log: {log_path}")


def read_env(path: Path) -> tuple[str, dict[str, str]]:
    text = path.read_text(encoding="utf-8-sig") if path.exists() else ""
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key, value = stripped.split("=", 1)
            values[key.strip()] = value.strip().strip('"').strip("'")
    return text, values


def update_frontend_env(path: Path, url: str) -> dict[str, str]:
    text, values = read_env(path)
    lines = text.splitlines()
    updated = False
    for index, line in enumerate(lines):
        if line.strip().startswith("VITE_BACKEND_TARGET="):
            lines[index] = "VITE_BACKEND_TARGET=" + url
            updated = True
            break
    if not updated:
        lines.append("VITE_BACKEND_TARGET=" + url)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    _, values = read_env(path)
    return values


def verify_ready(url: str, token: str) -> dict:
    request = urllib.request.Request(
        url.rstrip("/") + "/ready",
        headers={"Accept": "application/json", "Authorization": "Bearer " + token,
                 "ngrok-skip-browser-warning": "true"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.loads(response.read())
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise AutomationError(f"Remote readiness failed: HTTP {exc.code}: {body}") from exc
    if payload.get("ready") is not True:
        raise AutomationError("Remote backend is not ready: " + json.dumps(payload, ensure_ascii=False))
    return payload


def start_frontend() -> int:
    if os.name == "nt":
        return subprocess.call(["cmd.exe", "/c", str(ROOT / "run.bat"), "frontend"], cwd=ROOT)
    return subprocess.call(["npm", "run", "dev"], cwd=ROOT / "frontend")


def action_start(args, settings: dict) -> int:
    kaggle = ensure_kaggle_cli()
    ensure_authentication(kaggle)
    ref = git_ref()
    fingerprint = automation_fingerprint(settings, ref)
    bundle = write_kernel_bundle(settings, ref, fingerprint)
    handle = settings["kernel"]
    exists, status, status_text = kernel_status(kaggle, handle)
    print(status_text.strip() or f"Kernel {handle}: not created", flush=True)
    state_path = bundle / "automation-state.json"
    previous = {}
    if state_path.exists():
        previous = json.loads(state_path.read_text(encoding="utf-8"))
    if exists and status in ACTIVE_STATES:
        if previous.get("fingerprint") and previous["fingerprint"] != fingerprint:
            print("Cảnh báo: kernel đang chạy commit cũ; giữ phiên hiện tại để tránh tạo run trùng.", flush=True)
        print("Tái sử dụng Kaggle kernel đang chạy; không push version mới.", flush=True)
    else:
        command = [kaggle, "kernels", "push", "-p", str(bundle),
                   "--accelerator", settings.get("machine_shape", "NvidiaTeslaT4"),
                   "--timeout", str(int(settings.get("kernel_run_timeout_seconds", 43200)))]
        print("Đang tạo/cập nhật đúng một Kaggle notebook và khởi chạy...", flush=True)
        pushed = run_capture(command)
        print(pushed.stdout, flush=True)
        if pushed.returncode:
            raise AutomationError("Kaggle kernel push failed")
        state_path.write_text(json.dumps({"fingerprint": fingerprint, "ref": ref,
                                          "updated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}, indent=2) + "\n",
                              encoding="utf-8")
    url, log_path = wait_for_backend_url(kaggle, settings)
    env_path = ROOT / settings.get("frontend_env", "frontend/.env")
    values = update_frontend_env(env_path, url)
    token = values.get("BACKEND_PROXY_TOKEN", "")
    if not token:
        raise AutomationError(f"Đã nhận URL {url}, nhưng {env_path} chưa có BACKEND_PROXY_TOKEN")
    ready = verify_ready(url, token)
    print("REMOTE_BACKEND_URL=" + url, flush=True)
    print("Frontend env updated:", env_path, flush=True)
    print("Remote ready; build_id=", ready.get("compatibility", {}).get("build_id"), flush=True)
    print("Local Kaggle log:", log_path, flush=True)
    if args.no_frontend or not settings.get("start_frontend", True):
        return 0
    print("Khởi động frontend local...", flush=True)
    return start_frontend()


def action_status(settings: dict) -> int:
    kaggle = ensure_kaggle_cli(); ensure_authentication(kaggle)
    exists, status, output = kernel_status(kaggle, settings["kernel"])
    print(output, end="" if output.endswith("\n") else "\n")
    return 0 if exists else 1


def action_logs(settings: dict) -> int:
    kaggle = ensure_kaggle_cli(); ensure_authentication(kaggle)
    result = fetch_logs(kaggle, settings["kernel"])
    print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
    return result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("start", "status", "logs"), nargs="?", default="start")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--no-frontend", action="store_true")
    args = parser.parse_args()
    settings = load_settings(args.config)
    if args.action == "start": return action_start(args, settings)
    if args.action == "status": return action_status(settings)
    return action_logs(settings)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AutomationError, subprocess.CalledProcessError) as exc:
        print("KAGGLE ONLINE ERROR:", exc, file=sys.stderr)
        raise SystemExit(1)
